apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pipelineversions.pipelines.kubeflow.org
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/webhook-serving-cert
webhooks:
  - name: pipelineversions.pipelines.kubeflow.org
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v2beta1
        resources:
          - pipelineversions
        scope: Namespaced
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: ml-pipeline-reverse-proxy
        namespace: kubeflow
        path: /webhooks/mutate-pipelineversion
        port: 9443
