apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
  - ./base/pipelines.kubeflow.org_pipelines.yaml
  - ./base/pipelines.kubeflow.org_pipelineversions.yaml

patches:
  # This patch is required because the kubebuilder defaults don't seem to work for arrays.
  - target:
      version: v1
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: pipelineversions.pipelines.kubeflow.org
    patch: |-
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/status/default
        value:
          conditions:
            - type: PipelineVersionStatus
              reason: READY
              message: READY
              status: "True"
